What are you doing mateo
bkarpati/git_workshop pull request #12
Opened 2022-06-13 12:26 UTC by Raphael-ML-Picard

Oui oui
Some name to it

2022-06-13 12:30 UTC, Raphael-ML-Picard commented
@Paijmans Can you please review my beautiful code?

2022-06-13 12:35 UTC, Paijmans requested changes
- Good name for water storage.
- New leave shape

2022-06-13 12:35 UTC, Paijmans commented on release_notes.md
> +- Added the `cone` functionality to support data export
This is amazing! Compliments.

2022-06-13 12:35 UTC, Paijmans commented on sequioa/crown.md
> +TODO: Secure the exported file
Please change the shape of the leaves!

2022-06-13 12:35 UTC, Paijmans commented on sequioa/trunk.md
> +
Please add water storage and find out a good name.

2022-06-13 12:37 UTC, Raphael-ML-Picard commented on release_notes.md
> +- Added the `cone` functionality to support data export
Thanks you Dr. Paijmans

2022-06-13 12:42 UTC, mateohv commented
I have no idea what I am doing

2022-06-23 11:59 UTC, bkarpati commented
Thanks for participating in the Git workshop. I'm going to close this PR for now and also delete the remote branch.
Please stay tuned for the follow-up.

2022-06-23 11:59 UTC, closed without merging