Updated water storage and curly leaves because Bence asked us to.
bkarpati/git_workshop pull request #31
Opened 2022-06-13 12:31 UTC by Limhes

2022-06-13 12:38 UTC, thms317 requested changes
Unhappy, please change everything.

2022-06-13 12:38 UTC, thms317 commented on sequioa/crown.md
> +Has a nice curly shape for extra pleasure.
This comment is sooooo inappropriate, I feel offended

2022-06-13 12:38 UTC, thms317 commented on sequioa/trunk.md
> +In case the tree gets thirsty. Buckets full of juicy water.
Please rename to juice-bucket

2022-06-13 12:43 UTC, Limhes commented on sequioa/crown.md
> +Has a nice curly shape for extra pleasure.
Your offence makes me sad. Crying silently

2022-06-23 11:51 UTC, bkarpati commented
Thanks for participating in the Git workshop. I'm going to close this PR for now and also delete the remote branch.
Please stay tuned for the follow-up.

2022-06-23 11:51 UTC, closed without merging